### ISSUE TITLE
"zero in sympy"...

### ISSUE THREAD

**Issue by zolabar** [im-AMS/Conformal-Maps#11]
There is a sympy issue (we could check if we create an issue there) concerning "zero", what is zero?

x, y, c, d = symbols('x, y, c, d', real = True) 

f=(7.6*I*(x + I*y) - 15.3215831575369*I)/(-2.01599778388644*x - 2.01599778388644*I*y + 1)

gives

simplify(diff(im(f), y)-diff(re(f), x)) equal to somethin of the order 10**(-16)
simplify(diff(im(f), x)+diff(re(f), y)) equal to somethin of the order 10**(-16)

while

f=(7.6*I*(x + I*y) - c*I)/(-d*x - d*I*y + 1)
print()
print(simplify(diff(im(f), x)+diff(re(f), y)))
print()
print(simplify(diff(im(f), y)-diff(re(f), x)))
print()

gives zero...

[check_anyltic_sympy_issue.zip](https://github.com/im-AMS/Conformal-Maps/files/7121397/check_anyltic_sympy_issue.zip)

**Comment by im-AMS** [comment]
*I am not sure, but this is what I suspect*

I think its the issue with sympy, 10^-16 is in the order of machine zero aka machine epsilon( around 2.220446e-16 for 64 bit machine) so its essentially zero.

**Comment by zolabar** [comment]
@im-AMS , yes, but since for sympy it is not zero, one of the built in functions, which is conformal is said by analytic_check, that it is not…

**Comment by zolabar** [comment]
Fixed in current version of

https://github.com/zolabar/Conformal-Maps

with workaround disscussed in Problem 2 of

https://github.com/sympy/sympy/issues/22425#issuecomment-970247521
